export const ESPECIALIDADES: string[] = [
  'Clínico Geral',
  'Cardiologia',
  'Dermatologia',
  'Endocrinologia',
  'Ginecologia',
  'Neurologia',
  'Oftalmologia',
  'Ortopedia',
  'Pediatria',
  'Psicologia',
  'Psiquiatria',
  'Odontologia',
  'Urologia',
];